### ISSUE TITLE
Popover - add a delay prop so the delay on hiding and showing can be customised

### ISSUE THREAD

**Issue by s24y85u2** [Royal-Navy/design-system#1759]
### Description
We would like the ability to customise the delay in hiding and showing the popover.

**Comment by hxltrhuxze** [comment]
I've spoken to s24y85u2 to gain clarity on this ticket.

> We have a bunch of ‘bricks’ on the scheduler that on hover show the popover, however as the popover takes a few seconds as default to disappear when no longer being hovered over, you get overlapping. We would like to be able to say disappear in 1 second or half a second after the user stops hovering so that the do not overlap when waiting for them to disappear.

Things to explore:
- Reducing the delay when dismissing the popover
- When a popover is triggered to show, hide any other popovers that may be currently visible.

**Comment by thyhjwb6** [comment]
> Reducing the delay when dismissing the popover

We can expose a `closeDelay` which will be passed through to the hook and used for the existing `setTimeout`.


> When a popover is triggered to show, hide any other popovers that may be currently visible.

We can expose an `onVisible` or `onOpen` prop so that the application can be responsible for maintaining the active `Popover` in state and then set a prop `isOpen` to `false` for the `Popover` that needs closing.


Names might change but those are the sketched out ideas.

**Comment by thyhjwb6** [comment]
Having spoken with @s24y85u2:

> for us, having control over the delay, so there dont hang around for ages while others are open is all we need
