### ISSUE TITLE
Context menu does not support nested elements in 2.26.0 and above

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#1818]
### Steps to reproduce
Create a context menu associated with markup that has nested elements, i.e.

```jsx
<>
    <div
      ref={ref}
      style={{
        display: 'inline-block',
        padding: '1rem',

        backgroundColor: '#c9c9c9',
      }}
    >
      <p
        style={{
          display: 'block',
          padding: '1rem',
          margin: '1rem',
          backgroundColor: 'pink',
        }}
      >
        This is a test
      </p>
      <p
        style={{
          display: 'block',
          padding: '1rem',
          margin: '1rem',
          backgroundColor: 'green',
        }}
      >
        This is another test
      </p>
    </div>

    <ContextMenu
      attachedToRef={ref}
      onHide={action('onHide')}
      onShow={action('onShow')}
    >
      <ContextMenuItem
        icon={<IconEdit />}
        link={<Link href="/edit">Edit</Link>}
      />
      <ContextMenuItem
        icon={<IconDelete />}
        link={<Link href="/delete">Delete</Link>}
      />
      <ContextMenuItem link={<Link href="/delete">Action</Link>} />
      <ContextMenuDivider />
      <ContextMenuItem
        icon={<IconAdd />}
        link={<Link href="/add">Add</Link>}
      />
      <ContextMenuDivider />
      <ContextMenuItem
        link={<Link href="/something-else">Do something else</Link>}
      />
      <ContextMenuDivider />
      <ContextMenuItem
        link={
          <Link href="/something-else">
            This is too much text to put into a context menu item
          </Link>
        }
      />
    </ContextMenu>
  </>
```

When you try to right click on one of the nested elements it does not show the context menu, if you right click on the parent element it does.

**Comment by s24y85u2** [comment]
I second this issue, we have a table where the attachedToRef is the 'tbody' so when right clicking on a 'tr' or 'td' that is nested in the 'tbody' it no longer shows the context menu. It seems the move away from using attachedToRef.current.getBoundingClientRect() in this commit: https://github.com/Royal-Navy/design-system/commit/6f32dd3ba24c05e2f9f9d074a9a2a9073cd95a5e is the issue as you now just check e.target === attachedToRef.current rather than isWithinBoundingBox(bottomLeft, topRight, mousePoint).

This breaks our functionality so is blocked us a fair bit.

**Comment by m7kvqbe1** [comment]
Thank you for the issue ticket.

Appears to be a regression introduce in `2.6.0` (https://github.com/Royal-Navy/design-system/commit/6f32dd3ba24c05e2f9f9d074a9a2a9073cd95a5e). 

We will investigate and fix this upcoming sprint (commencing Thursday).

**Comment by antictor** [comment]
You mean 2.26.0 ? 

Found a fix and raising PR.
