### ISSUE TITLE
Add Masthead component

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#187]
Applications require a top bar that communicates the application/service name and optionally provides features for: search, user profile info, notifications and navigation.

The Masthead may or may not be used in conjunction with the Sidebar.

The Masthead needs to be modular to the application in question is able to use any combination of its features, including all or none of them.

Currently we don't have any applications that require the Masthead to support mobile, but this will come in time.

As this is potentially complex it may be worth creating the Masthead in stages, though the design should include all options to ensure that it will evolve without issue.

Initially the primary project for this simply requires the ability to display a logo and service name.  

Another project, re-starting soon will also require the user profile section to be added.  

Finally there is a project being worked on elsewhere that requires a Masthead including search and navigation.

<img width="1038" alt="Screenshot 2019-08-01 at 14 13 44" src="https://user-images.githubusercontent.com/48056118/62296409-e9948780-b466-11e9-8dcb-2c3a3cd56929.png">

<img width="1097" alt="Screenshot 2019-08-01 at 14 14 17" src="https://user-images.githubusercontent.com/48056118/62296347-cc5fb900-b466-11e9-8e6d-ad1078135eb1.png">

<img width="501" alt="Screenshot 2019-08-01 at 14 13 56" src="https://user-images.githubusercontent.com/48056118/62296348-cc5fb900-b466-11e9-843b-62eacbec05e1.png">

<img width="516" alt="Screenshot 2019-08-01 at 13 29 25" src="https://user-images.githubusercontent.com/48056118/62295964-1a27f180-b466-11e9-8323-f0e50519844f.png">

**Comment by antictor** [comment]
Creating a basic version first that just has the logo and service name for current project.

**Comment by hxltrhuxze** [comment]
I've updated both the mobile and desktop comps to include placement for:
- Search
- Notifications
- Profile

---

## Desktop Masthead
The Desktop version of the Masthead keeps the placement of the Notification Badge and the Profile Avatar, however adds the ability to have a Search Button next to them.

When the Search Button is clicked, the new Search Bar replaces the the nav with a dark background input. The input takes up the full height of the nav.

<img width="790" alt="Screenshot 2019-08-05 at 16 30 58" src="https://user-images.githubusercontent.com/48090803/62476226-7ceaf700-b79e-11e9-8852-156ec067da40.png">

---

## Mobile Masthead
To maintain usage consistency, not a lot has changed between the desktop and mobile versions of the Masthead.

The Search Bar still functions the same as it does on desktop - clicking the Search Button will open the bar over the Nav. Clicking it again will revert the UI.

The Nav Links sit within a container that overflows on the `x-axis`. This removes the need for a separate dropdown mobile menu.

<img width="441" alt="Screenshot 2019-08-05 at 16 31 05" src="https://user-images.githubusercontent.com/48090803/62476227-7d838d80-b79e-11e9-80ce-f96be06fb826.png">

---

## Notification Sheet

The notification sheet now behaves slightly different on Desktop and Mobile. On Desktop, the regular Notification Sheet stays in its popover, just below the Notification Button. On Mobile, when the Notification Button is clicked, the Notification Sheet now becomes full screen. The bars at the top and bottom of the Sheet are fixed in place, with the list of notifications becoming a scrolling list.

<img width="783" alt="Screenshot 2019-08-05 at 16 31 10" src="https://user-images.githubusercontent.com/48090803/62476229-7d838d80-b79e-11e9-95f9-344c22d9b153.png">

**Comment by antictor** [comment]
ok I'll make a start

**Comment by 09txzS1qs** [comment]
Both look good generally. 2 questions: 

* Mobile masthead: Like the overflow on the X axis rather than dropdown, however is it worth having an arrow pointing left to indicate you can swipe to see more options rather than half cut off words like "calend-" ? Might be overkill or be less clear. 
* For full screen notifications, could we have headings? So Notficiations is a bit bigger, and then we have sub headings for time. Attached Jira mobile Notifications screenshot as a reference for what I mean.

**Comment by antictor** [comment]
Any chance of a Sketch file to go with this or something we can inspect?

**Comment by antictor** [comment]
Can you add focus states for the search/notification/avatar links/buttons for people using keyboard navigation?
