### ISSUE TITLE
DatePicker tab order bug

### ISSUE THREAD

**Issue by k9dh3zij** [Royal-Navy/design-system#2177]
Scenario:
- Click on date picker text field
- Press Tab once. Focus is now on the 'collapse' arrow (even though it's not visible - raising a separate bug for that)
- Tab again. Focus is now on something else, outside the DatePicker (not sure what)
- Tab again. Focus moves to the DatePicker calendar.
(see comments below for demo)

**Expected tab order** 
(should work in both directions: tab / shiftTab)

Focus on text field
[Tab]
Focus on DatePicker collapse/expand arrow - pressing Enter collapses/expands the Calendar sheet
[Tab]
Focus on Calendar sheet left arrow - pressing Enter changes to previous month and maintains focus on the left arrow
[Tab]
Focus on Calendar right arrow - pressing Enter changes to next month and maintains focus on the right arrow
[Tab]
Focus on Calendar selected date - at this stage, the user should be able to choose a date using the up/down/left/right keyboard arrows and pressing Enter. Pressing Enter changes the date input to the selected one, hides the Calendar sheet and moves focus back to the DatePicker expand/collapse arrow.

**Comment by k9dh3zij** [comment]
Notice the focus moving to the extra text field, then back to the visual calendar

![Demo of bug with an extra textfield added](https://user-images.githubusercontent.com/73531035/113885305-a64ff780-97b7-11eb-9134-581d871277ca.gif)

**Comment by thyhjwb6** [comment]
The tab order of the calendar is because of the position of the div and could be addressed by moving the calendar flush to the left.

**Comment by m7kvqbe1** [comment]
https://github.com/danreeves/react-tether

Takes the container out of the normal DOM flow and moves it to the root so that it can be intelligently positioned.

Some things to consider / test for if looking to find an alternative to the positioning library:

- Overflow issues when component is consumed within another container
- The component must maintain position when the user scrolls the viewport
- You should be able to position the component left, right, above, below the DatePicker input

**Comment by m7kvqbe1** [comment]
This ticket is blocked by https://github.com/Royal-Navy/design-system/issues/1642
