### ISSUE TITLE
Copy existing `NumberInput` to `NumberInputE`

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#2434]
> Number inputs let users enter new or change existing numbers, either by editing the number directly or using the input controls.

- [x] Copy component
- [x] Apply CSS changes
  - [x] Update prefix
  - [x] Update suffix
  - [x] Update buttons

[Design spec](https://docs.google.com/document/d/1yXF0wUUvvsH88j9bn-PGc9VD3zr75tAC78uuXfFCoNs/edit#heading=h.9dpux7wjjbeb)

**Comment by SudoSloth** [comment]
Hello, I'm currently using the NumberInput Formik component, wrapped in a formik field in a React project in which the component currently doesn't step through floating point number correctly, forcing me to have to use a text input in its place. 

For example, using a step of 0.01, results in the following:
- 123
- 123.01
- 123.02000000000001
- 123.03000000000002
- 123.04000000000002
- 123.05000000000003
- 123.06000000000003
- 123.07000000000004
- 123.08000000000004
- 123.09000000000005
- 123.10000000000005

I've updated the react component package recently looking to migrate to NumberInput again and this issue is still occurring. Can I assume that a fix for this issue (which is probably a duplicate of #1128 which has since gone stale) will be part of the acceptance criteria of this new number field? Can you recommend a preferred pattern whilst I wait for a release?

**Comment by hxltrhuxze** [comment]
Can we also investigate this issue before we complete this work too? https://github.com/Royal-Navy/design-system/issues/1767
