### ISSUE TITLE
(Spike) Investigate ways of measuring React Component Library performance

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#2495]
Experiment with and document ways in which to measure performance of individual components:

- First paint
- Re-renders
- File size
- Smoothness of interactions
- Cross browser

Leverage tooling against a single component as POC.

Output should be a POC of integrated tooling ready to be integrated into CI.

**Comment by thyhjwb6** [comment]
## Performance analysis

### Tools investigated
- [Storybook Performance Addon](https://github.com/atlassian-labs/storybook-addon-performance/)
- [Why Did You Render](https://github.com/welldone-software/why-did-you-render)
- [@shopify/react-performance](https://github.com/Shopify/quilt/tree/main/packages/react-performance)
- [Cypress and `performance.mark`](https://spin.atomicobject.com/2021/04/21/writing-performance-tests-cypress/)
- [Cypress and Google Lighthouse](https://applitools.com/blog/using-cypress-google-lighthouse-performance-testing/)

### Storybook Performance Addon results
The performance addon was used to better understand how our components perform.

Some notes about this data:
- `Timeline` does not appear quite right and this is probably because the initial load is synchronous and then the rows are populated asynchronously.
- `Select` appears to be not performing well which brings into question the performance of `react-select`
- It does not include all components
- Some components seem to perform worse when considering number of DOM elements, examples are text inputs, `DatePicker` and `Tooltip`.
- The rerender performance of some components could be improved, examples are `NumberInput`, `TextAreaE`, `DismissibleBanner`, `DataList`, `CheckboxEnhanced`

The following data was collected when running the test for 100 samples against each component:

| Component | Initial render | Rerender | DOM element count | Complete render |
|-----------|----------------|----------|-------------------|-----------------|
|Timeline	|1.12           |7.54	|1	|10.38|
|Select	|6.45	|1.71	|18	|7.54|
|Sidebar E|	2.75|	1.49|	41|	5.68|
|Masthead	|3.08|	1.65| 	39|	5.53|
|Date Picker|	3.12	|0.92	|10	|4.92|
|List	|2.28	|1.17|	41|	4.39|
|Alert	|1.35|	0.5|	10	|4.32|
|Dropdown|	2.66|	1.59|	13	|4.23|
|Tab Set|	1.77|	0.98|	20|	4.03|
|Pagination	|2.23	|0.95	|27|	4|
|Table| 1.79|	0.93|	22|	3.79|
|Progress Indicator|	1.53|	0.5|	9	|3.72|
|Number Input|	1.65	|1.39|	11|	3.66|
|Range Slider|	2.61|	1.12|	29|	3.62|
|Breadcrumbs|	1.54|	0.58	|14|	3.41|
|Data List|	2.01	|1.32	|26	|3.41|
|Sidebar	|1.54|	0.7	|21	|3.37|
|Dismissible Banner|	1.42|	0.94|	12	|3.28|
|Button Group|	2.15|	1.02|	11	|3.02|
|Switch|	1.52|	0.64	|10	|3|
|Drawer|	1.28|	0.6|	9|	2.98|
|Text Input	|1.06	|0.4	|5	|2.87|
|Checkbox Enhanced|	1.6|	0.99|	7	|2.85|
|Button|	0.88	|0.36|	2	|2.84|
|Nav|	1.24|	0.56	|12	|2.75|
|Avatar|	0.91|	0.2|	1|	2.73|
|Popover|	1.17|	0.42	|2|	2.62|
|Text Area	|1.17|	0.68	|5|	2.52|
|Text Input E|	0.96|	0.46|	5	|2.51|
|Tab Nav	|1.24|	0.45	|8|	2.43|
|Text Area E	|1.13|	0.89|	4	|2.42|
|Radio Enhanced|	1.26|	0.62|	6|	2.4|
|Radio|	1.13|	0.44|	5	|2.35|
|Phase Banner|	1.04|	0.32|	5	|2.3|
|Checkbox	|1.47|	0.61|	5	|2.24|
|Tooltip|	0.91|	0.44|	3|	2.19|
|Badge|	0.84	|0.21	|1|	1.9|
|Panel	|0.87	|0.24	|1|	1.8|
|Card Frame|	0.91	|0.22	|1	|1.73|


### Why Did You Render
This was used within unit testing scenarios to see if there are unnecessary renders. It appears that we have room for improvement.

[Common Fixing Scenarios](https://medium.com/welldone-software/why-did-you-render-mr-big-pure-react-component-part-2-common-fixing-scenarios-667bfdec2e0f)

```
  describe('when looking for rerenders', () => {
    let updateInfos: UpdateInfo[]

    beforeEach(async () => {
      updateInfos = []
      whyDidYouRender(React, {
        // logOnDifferentValues: true,
        notifier: (updateInfo) => updateInfos.push(updateInfo),
      })

      wrapper = render(<TextInputE label="label" name="name" type="password" />)
      // wrapper.rerender(<TextInputE label="label" name="name" type="password" />)

      await userEvent.type(wrapper.getByTestId('text-input-input'), 'a')

      return waitFor(() => {
        expect(wrapper.getByTestId('text-input-input')).toHaveValue('a')
      })
    })

    it('should not rerender unnecessarily', () => {
      console.log(JSON.stringify(updateInfos[0]))
      console.log(JSON.stringify(updateInfos[1]))
      console.log(JSON.stringify(updateInfos[2]))

      expect(updateInfos).toHaveLength(0)
    })
  })
```

### Bundle size
We currently have a bundle size of 6.4mb. It might be perceived that it is large vs a competing design system, but this would be a false negative once tree shaking has been completed by downstream applications.

The reason for our bundle size is that we include source maps which help with debugging.

Without sourcemaps we could have a bundle size of < 1mb.

We need to consider whether we want to reduce our bundle size which will clearly advertise to consumers that RN Design System is light. If we do this then the trade off is that consumers will not get source maps and find applications harder to debug if there is a problem.


### Suggested next steps
- Get the Storybook Performance Addon working with the `react-component-library` Storybook implementation. Suspected issue is Webpack.
- Consider automating the benchmarking of performance on a regular basis
- Work towards improving the performance of the worst performing components (factoring in complexity of the component)
- Monitor performance of interactions within more complex components
- Consider evolving the Coffee App to run performance benchmarking against
  - Consider using Gatling to stress test
- Consider the use of Cypress for running the performance benchmarking
- Consider removing source maps from the bundle. `npm publish --dry-run` is useful here (the downside is that consumers could have debugging issues)
- If we are committing to a smaller bundle size then make this part of the CI pipeline
- Act upon "Why Did You Render" issues
  - Remove instances of `style={}`
  - Consider using `React.memo` more (will help with rerender data points too)
  - Integrate in unit tests
  - Start small

**Comment by thyhjwb6** [comment]
[Performance foundation implementation](https://github.com/Royal-Navy/design-system/milestone/37)

More tickets will be created once the foundation is complete.
