### ISSUE TITLE
Use production build of React for live Storybook deployment

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#2602]
Created from #2495

Our [live version](https://storybook.royalnavy.io/) is not using the production build of React.

![Screenshot 2021-07-22 at 09 57 38](https://user-images.githubusercontent.com/56078793/126613860-c7253bb5-02ad-4f9f-9056-eb6f0b890a00.png)

**Comment by jpveooys** [comment]
Looks like the production version is being used to me as profiling is unavailable:

Local:

![image](https://user-images.githubusercontent.com/66470099/160856811-93ce155f-5f89-458f-9a58-3a836b4afedc.png)

https://storybook.design-system.digital.mod.uk:

![image](https://user-images.githubusercontent.com/66470099/160857096-3b6e64c8-9b15-411f-9c84-f6849e4d9154.png)

A grep of the bundle also confirms `react.production.min.js` is included (and not `react.development.js`).

(The dev tools still otherwise mostly work in a prod build.)
