### ISSUE TITLE
UUID prevents snapshot testing of SidebarUserE

### ISSUE THREAD

**Issue by ARChilton** [Royal-Navy/design-system#2656]
### Steps to reproduce

1. create a snapshot test of the sidebar with <SidebarUserE /> in it, or add storyshots to your storybook implementation.
2. run jest tests
3. Each time it runs there is a UUID id created on the Sheet component which shows up on the snapshot's HTML mark-up and breaks the test.

The <Sheet /> component is the cause of the UUID but there isn't a prop to provide an ID like other places UUID has been used.

### Minimal reproduction

Contact me via the NDS slack and I can show you should you require.

**Comment by m7kvqbe1** [comment]
The `Sidebar` notifications sheet now maintains a static ID. There are few small points worth noting:

- This `Sidebar` component is marked as deprecated and we recommend instead using `SidebarE`. The `Sidebar` implementation is due to be removed in the next major `3.x.x` release.

- We usually avoid Jest snapshot testing (https://medium.com/@tomgold_48918/why-i-stopped-using-snapshot-testing-with-jest-3279fe41ffb2). We used to write snapshot tests and have since removed them from the design system.
