### ISSUE TITLE
Using library icons increases bundle size and breaks build

### ISSUE THREAD

**Issue by antictor** [Royal-Navy/design-system#289]
If I include an icon from `@royal-navy/icon-library` in the react component library the compile time goes from 6 seconds to 30+ seconds and the bundle size increases by almost a megabyte.

If I include an icon from `@royal-navy/icon-library` in a markdown file int the documentation site the build time goes from a minute to about 8 minutes and this also causes Netlify to fail as the build times out.

For both options we need to find why it is in effect trying to re-compile the icons and how to tree shake so that in the case of the component library it only includes the icons needed which should barely affect the bundle size.

**Comment by m7kvqbe1** [comment]
So, what we've learned is that in order to take advantage of tree shaking, you must...

- Use ES2015 module syntax (i.e. import and export).
- Ensure no compilers transform your ES2015 module syntax into CommonJS modules (this is the default behavior of the popular Babel preset @babel/preset-env.
- Add a "sideEffects" property to your project's package.json file.
- Use the production mode configuration option to enable various optimizations including minification and tree shaking.
