### ISSUE TITLE
Smoke test failing following React 18 release

### ISSUE THREAD

**Issue by jpveooys** [Royal-Navy/design-system#3213]
`npx create-react-app@latest --template defencedigital myapp` is failing following the release of React 18 due to peer dependency errors:

```
Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template-defencedigital...


added 1370 packages in 39s

169 packages are looking for funding
  run `npm fund` for details

Initialized a git repository.

Installing template dependencies using npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @apollo/client@3.5.10
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"^18.0.0" from react-dom@18.0.0
npm ERR!   node_modules/react-dom
npm ERR!     react-dom@"^18.0.0" from the root project
npm ERR!     peer react-dom@"*" from @testing-library/react@12.1.4
npm ERR!     node_modules/@testing-library/react
npm ERR!       @testing-library/react@"^12.1.2" from the root project
npm ERR!     1 more (styled-components)
npm ERR!   peer react@">= 16" from react-scripts@5.0.0
npm ERR!   node_modules/react-scripts
npm ERR!     react-scripts@"5.0.0" from the root project
npm ERR!   4 more (the root project, @testing-library/react, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional react@"^16.8.0 || ^17.0.0" from @apollo/client@3.5.10
npm ERR! node_modules/@apollo/client
npm ERR!   @apollo/client@"^3.5.6" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0" from @apollo/client@3.5.10
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.5.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Blog post on React 18:

https://reactjs.org/blog/2022/03/29/react-v18.html

**Comment by c9qsm62x** [comment]
We've also had issues with React 18 when using Code Sandbox and a quick smoke test in our app. 
One of the way we got round it was to force the peer dependencies to use React 18.
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

This was cause by an unmaintained lib https://github.com/jossmac/react-toast-notifications. 
https://github.com/jossmac/react-toast-notifications/blob/2089a9e3511709e5194f1dd77a04d71eadbcb0b1/package.json#L72-L75

Are there any plans to update this toast in the app to not use react-toast-notifications

**Comment by m7kvqbe1** [comment]
@jpveooys 

The problem seems to be `@apollo/client@3.5.10` (latest) in the CRA template. 

They've a peer dependency range set for React of [`^16.8.0 || ^17.0.0`](https://github.com/apollographql/apollo-client/blob/3d09a63f8e859e57fd8065c49e8f0f3787191be0/package.json#L68).

I've tried numerous workarounds including the overrides trick to no avail. Looks like we have the choice of either removing it from the CRA template or holding out a little bit longer and hoping for a bump in the supported range.

I've opened a [ticket](https://github.com/apollographql/apollo-client/issues/9612) upstream.

RTL also creates an issue but that's an easy fix with a bump to the next major.

There are a few [manual workarounds](https://stackoverflow.com/questions/71835697/create-react-app-dependency-version-issues-with-react-18/71841860) for consumers of the CRA template to follow - but these don't help us with the smoketest.

I've marked this as blocked for now and will re-visit over the next few days.

----

@c9qsm62x re: react-toast-notificaitons

That component hasn't been touched in a long time.

I've created a [ticket](https://github.com/defencedigital/mod-uk-design-system/issues/3246) to look into removing reliance on that unmaintained dependency.

**Comment by m7kvqbe1** [comment]
Looks like `@apollo/client` have just shipped a pre-release of the next minor that should fix this.

Picking this back up today.

**Comment by jpveooys** [comment]
@m7kvqbe1 

I added overrides here:

https://github.com/defencedigital/mod-uk-design-system/commit/8e9da86a6e662875f28c11d801fe67f9bd91184c#diff-f00100e4c0b71343aacaa479809f7b08efb7e0f0fbb1d68677dfa24c0a8540d7R36-R39

and it did bypass the peer dependency errors:

https://github.com/defencedigital/mod-uk-design-system/runs/6108783518?check_suite_focus=true

(But it doesn't mean everything works, of course, and it'd be better if the dependencies has proper React 18 support.)
