### ISSUE TITLE
Label text is not vertically middle for `Button` in Firefox

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#3544]
Appears to be out by 1px.

### Screenshot
<img width="170" alt="Screenshot 2022-12-07 at 14 16 25" src="https://user-images.githubusercontent.com/56078793/206202367-4f764153-4131-492f-93bd-d6879919da43.png">

**Comment by jpveooys** [comment]
Hi @thyhjwb6 :wave: 

Was that screenshot taken on Linux? The vertical centring is, unfortunately, dependent on all of the font, browser and OS. In Firefox on Windows the positioning is lower, for example:

![image (4)](https://user-images.githubusercontent.com/66470099/206232241-5234ca4e-d2a0-4b38-acda-e3a0a7792446.png)

There's a similar long-standing problem on GitHub on Ubuntu, for example: https://github.com/primer/css/issues/1209

Have assigned this as size medium due to the number of factors involved.

**Comment by jpveooys** [comment]
Some useful links and info for future reference.

Arial on Firefox and Ubuntu (slightly lower than Lato):

![image](https://user-images.githubusercontent.com/66470099/206240193-9dbfebba-5ad8-461f-8d2e-21da22369aac.png)

Article on font vertical metrics:

https://www.maxkohler.com/posts/2022-02-19-fixing-vertical-metrics/

Font vertical metrics analyser:

https://vertical-metrics.netlify.app/

![image](https://user-images.githubusercontent.com/66470099/206239625-ebe4e57e-05f0-4bba-bbb4-468d3648340a.png)
